In [1]:
import h5py as h5
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
a = np.logspace(-0.5, 2.0, 50)
e = np.linspace(0, 1, 51)
i = np.linspace(0, 180, 52)

grid_shape = (len(a), len(e), len(i))

In [3]:
densities = np.load("small_densities.npy")

In [5]:
normalised_density = densities / densities.sum()

In [112]:
e_dens = densities.reshape(grid_shape).sum(axis=0).sum(axis=1)
np.cumsum(e_dens / e_dens.sum())

array([0.00621046, 0.02244382, 0.05799355, 0.12572651, 0.18350645,
       0.2540331 , 0.34451746, 0.42282857, 0.49205289, 0.57354883,
       0.67764114, 0.76437937, 0.81996865, 0.86773183, 0.90253666,
       0.92513128, 0.94092469, 0.95198468, 0.9603459 , 0.96824434,
       0.97358179, 0.97737818, 0.98013052, 0.98249415, 0.98459027,
       0.98646538, 0.98815058, 0.98968759, 0.991062  , 0.99226926,
       0.9933425 , 0.99427463, 0.99507809, 0.99576195, 0.99634806,
       0.99685459, 0.99729565, 0.99768098, 0.99802002, 0.99831887,
       0.99858213, 0.99881367, 0.9990176 , 0.99919763, 0.99935689,
       0.99949789, 0.99962282, 0.99973374, 0.99983251, 0.9999208 ,
       1.        ])

In [120]:
e[1:]

array([0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.22,
       0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42, 0.44,
       0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64, 0.66,
       0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86, 0.88,
       0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ])

In [6]:
cumulative_density = normalised_density.cumsum()

In [98]:
random_values

array([0.16124326, 0.5467947 , 0.31091852, ..., 0.75870669, 0.55954472,
       0.30524412])

In [58]:
pixels = np.searchsorted(cumulative_density, random_values)

In [61]:
unique_pixels, counts = np.unique(pixels, return_counts=True)

In [62]:
unique_pixels

array([     0,      1,      2, ..., 130114, 130842, 131618])

In [66]:
x = list(range(2))
y = list(range(3))
z = list(range(4))

In [69]:
np.arange(2 * 3 * 4).astype(int).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [85]:
a_ind, e_ind, i_ind = np.unravel_index(pixels, shape=grid_shape)

In [92]:
e_ind

array([ 6,  6, 10, ..., 11,  7, 10])

In [97]:
e[-1]

1.0

In [94]:
e_ind.min()

0

In [89]:
a[a_ind]

array([2.32995181, 2.62039853, 2.32995181, ..., 2.62039853, 2.62039853,
       2.32995181])

In [84]:
np.random.rand(sum(counts))

array([0.10639891, 0.90254725, 0.32836886, ..., 0.93144453, 0.88701595,
       0.58697325])

In [82]:
a[a_ind]

array([  0.31622777,   0.31622777,   0.31622777, ..., 100.        ,
       100.        , 100.        ])

In [77]:
a_ind

array([ 0,  0,  0, ..., 49, 49, 49])

In [78]:
a

array([  0.31622777,   0.35564803,   0.39998234,   0.44984327,
         0.50591975,   0.5689866 ,   0.63991523,   0.71968567,
         0.80940012,   0.91029818,   1.02377397,   1.1513954 ,
         1.29492584,   1.45634848,   1.63789371,   1.84206997,
         2.0716984 ,   2.32995181,   2.62039853,   2.9470517 ,
         3.31442475,   3.72759372,   4.19226744,   4.71486636,
         5.30261134,   5.96362332,   6.70703561,   7.54312006,
         8.48342898,   9.54095476,  10.73030941,  12.06792641,
        13.57228783,  15.26417967,  17.16697907,  19.30697729,
        21.71374303,  24.42053095,  27.46474115,  30.88843596,
        34.73892112,  39.06939937,  43.93970561,  49.41713361,
        55.57736586,  62.50551925,  70.29732115,  79.06043211,
        88.91593339, 100.        ])

In [ ]:
def to_3d_index(index1d, shape=(50, 51, 52)):
    z = index1d / (shape[0] * shape[1])
    index1d -= (z * shape[0] * shape[1])

In [ ]:
public int[] to3D( int idx ) {
    final int z = idx / (xMax * yMax);
    idx -= (z * xMax * yMax);
    final int y = idx / xMax;
    final int x = idx % xMax;
    return new int[]{ x, y, z };
}

In [ ]:
131618

In [15]:
cumulative_density[45397:45400]

array([0.16089153, 0.17605004, 0.17790336])

In [22]:
indices = np.arange(len(densities)).astype(int)
shaped_indices = indices.reshape((len(a), len(e), len(i)))

In [28]:
results = np.where(np.isin(shaped_indices, np.array([45398, 48052])))

In [34]:
aei = np.array([results[0], results[1], results[2]])

In [35]:
aei.T

array([[17,  6,  2],
       [18,  6,  4]])

In [38]:
indices = np.arange(12).astype(int)
indices.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
ind = 7
7 // 4, 7 % 4

(1, 3)

In [57]:
np.searchsorted?

In [10]:
random_values = np.random.rand(int(1e7))